package com.spider.model;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.pdate
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    private String pdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.url
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.img
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author_id
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.pdate
     *
     * @return the value of article.pdate
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public String getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.pdate
     *
     * @param pdate the value for article.pdate
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public void setPdate(String pdate) {
        this.pdate = pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.url
     *
     * @return the value of article.url
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.url
     *
     * @param url the value for article.url
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.img
     *
     * @return the value of article.img
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.img
     *
     * @param img the value for article.img
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author_id
     *
     * @return the value of article.author_id
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author_id
     *
     * @param authorId the value for article.author_id
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated Thu Apr 21 10:04:41 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }
}