package com.spider.model;

import java.util.Date;

public class Author {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.id
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.wechat
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.open_id
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.create_at
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.update_at
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.id
     *
     * @return the value of author.id
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.id
     *
     * @param id the value for author.id
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.wechat
     *
     * @return the value of author.wechat
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.wechat
     *
     * @param wechat the value for author.wechat
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.open_id
     *
     * @return the value of author.open_id
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.open_id
     *
     * @param openId the value for author.open_id
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.create_at
     *
     * @return the value of author.create_at
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.create_at
     *
     * @param createAt the value for author.create_at
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.update_at
     *
     * @return the value of author.update_at
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.update_at
     *
     * @param updateAt the value for author.update_at
     *
     * @mbggenerated Wed Apr 13 15:26:10 CST 2016
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}